# site settings
title: Shreyash Desai
subtitle: Full Stack Developer
email: ShreyashDesai09@gmail.com
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ShreyashDesai09.github.io/" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Kolhapur
state: Maharashtra
zip_code: 416003
country: India
phone: +91 9422629500 / 7058127274

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/ShreyashDesai09
  GitLab: https://gitlab.com/shreyashdesai31796
  Google-Plus: 
  Instagram: https://www.instagram.com/sd_official_009/
  LinkedIn: https://www.linkedin.com/in/shreyash-desai-886979237/
  Twitter: https://x.com/Shreyas48859684
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
